### ISSUE TITLE
No left or right image on realsense d435

### ISSUE THREAD

**Issue by yhdurkaya** [ctu-mrs/mrs_simulation#23] opened 2022-06-01 16:15 UTC
Hello pals,
I have build the singularity container and I was working on a simulation. I realized that "enable_realsense_front" makes the drone spawn with a d435 sensor but there were some issues with topics that are published. Although I saw the image on /uav1/rgbd/color/image_raw topic, I couldn't see any output on the infra1 and infra2 topics. I assume that these are the stereo cameras topics that published left and right image.

I have just enabled the sensor and saw this. Do I need to enable some other config to see left and right images of the stereo camera or is it some kind of bug that I happened to see?

**Comment by yhdurkaya** [comment] 2022-06-02 08:00
Actually, as I checked it again, I saw that infra1 and infra2 doesn't publish anything on each of the nodes. I can see that topics under the aligned_depth_to_color and color works but not the other 2.

**Comment by yhdurkaya** [comment] 2022-06-02 08:55
With a little digging [https://github.com/IntelRealSense/realsense-ros](url) here, I found out that infra1and infra2 is disabled by default in realsense library. I tried to enable it by adding -enable_infra_rgb and such but it didn't work. Is there any way that I can add this to session.yml or anywhere else so that I can get the topics under infra1 and infra2 work?

**Comment by yhdurkaya** [comment] 2022-06-06 07:16
@klaxalk Hello again:) I have searched about this and couldn't come up with a solution. Do you have any idea on this topic?

**Comment by klaxalk** [comment] 2022-06-06 07:22
Hey, I think that nobody here needed to simulate (or use) the individual images since RealSense does quite a good job creating the depth on its own (and using its internal computational resources). So I think it's up to you to experiment with it. Maybe @stibipet or @matemat13 might know?

**Comment by stibipet** [comment] 2022-06-06 08:23
Nice catch, this is likely a bug in our model setup. The Realsense ROS plugin is not connecting to the infrared sensors. I'll do some digging and let you know once it's fixed.

**Comment by stibipet** [comment] 2022-06-06 08:39
@yhdurkaya Sorry about the delay, the issue is now fixed https://github.com/ctu-mrs/mrs_simulation/commit/54fbcc80e9daed6b8ab59f438a18f97072785470

**Closed by stibipet** 2022-06-06 08:39 UTC
Labels: bug
